DROP TABLE IF EXISTS address_book;
CREATE TABLE address_book
(
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- 自增主键
    user_id       BIGINT      NOT NULL,
    consignee     VARCHAR(50),
    sex           VARCHAR(2),
    phone         VARCHAR(11) NOT NULL,
    province_code VARCHAR(12),
    province_name VARCHAR(32),
    city_code     VARCHAR(12),
    city_name     VARCHAR(32),
    district_code VARCHAR(12),
    district_name VARCHAR(32),
    detail        VARCHAR(200),
    label         VARCHAR(100),
    is_default    BOOLEAN     NOT NULL DEFAULT FALSE
);

DROP TABLE IF EXISTS category;
CREATE TABLE category
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 自增主键
    name   VARCHAR(32) NOT NULL,                                -- 分类名称
    sort   INT         NOT NULL DEFAULT 0,                      -- 顺序
    status INT,                                                 -- 分类状态 0:禁用，1:启用
    CONSTRAINT idx_category_name UNIQUE (name)                  -- 唯一索引
);

INSERT INTO category (name, sort, status)
VALUES ('文学', 1, 1),
       ('历史', 2, 1),
       ('科幻', 3, 1),
       ('社会科学', 4, 1),
       ('哲学与宗教', 5, 1),
       ('艺术', 6, 1),
       ('教育', 7, 1),
       ('计算机', 8, 1),
       ('经济管理', 9, 1),
       ('医学', 10, 1);

DROP TABLE IF EXISTS book;
CREATE TABLE book
(
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- 自增主键
    name        VARCHAR(100) NOT NULL,                           -- 书名
    category_id BIGINT       NOT NULL,                           -- 所属分类ID
    price       NUMERIC(10, 2),                                  -- 价格，保留两位小数
    image       VARCHAR(255),                                    -- 封面图片URL
    description TEXT,                                            -- 书籍描述
    status      INTEGER      NOT NULL DEFAULT 1                  -- 状态（1=上架, 0=下架）
);

INSERT INTO book (name, category_id, price, image, description, status)
VALUES ('科学价值论', 4, 26.90,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/024618c32717404bbd6b74b75e686720.jpg',
        '科学思想的深度探索之作', 1),
       ('水浒全传', 1, 31.80,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/04d9249789a348f0ab198433e58f2cbb.jpg',
        '古典英雄传奇的巅峰巨著', 1),
       ('中国近代史', 2, 12.80,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/05780bb1a8ad4ff9a39b1187dd2ce268.jpg',
        '洞察近代中国的兴衰脉络', 1),
       ('球状闪电', 3, 67.30,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/075786e5ab0a4393801c134b9521903a.jpg',
        '硬核科幻与人文思考交融', 1),
       ('轻纱拂晓', 6, 42.80,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/0b704db434c14534a2a02d5da0327a24.jpg',
        '诗意文字勾勒岁月温情', 1),
       ('幸福之路', 5, 91.50,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/0c983cf890814fa9bf426b78ce57998e.jpg',
        '解锁幸福密码的哲学指南', 1),
       ('现代医学前沿', 10, 23.70,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/0c9a572668b242e880946c633edf78b9.jpg',
        '聚焦医学发展的前沿动态', 1),
       ('向上社交', 4, 78.10,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/0d0bdb1c9d754eb284497a7ac9cedea3.jpg',
        '高效社交的实用进阶宝典', 1),
       ('赵宋', 2, 19.40,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/160b3b8a7eb64402841985941d112485.jpg',
        '细说赵宋王朝的风雅与风骨', 1),
       ('资质通鉴', 2, 55.90,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/1832aa7140e84931b9483987193ff0ea.jpg',
        '通古今之变的史学经典', 1),
       ('活着', 1, 33.50,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/1a0e016d764e41c5a2b7ee3744f23a78.jpg',
        '直面生命本质的震撼之作', 1),
       ('社会医学', 10, 21.90,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/1fc118b546c94aed997e99b50f39af5e.jpg',
        '解析社会与健康的关联密码', 1),
       ('红楼梦', 1, 27.10,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/2907482c7cdf48be892cbec280b01ca6.jpg',
        '古典文学史上的巅峰绝唱', 1),
       ('成本管理', 9, 32.90,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/2c06ea0035364324a9956907b0f38c2d.jpg',
        '企业成本管控的实战指南', 1),
       ('教育的目的', 7, 18.00,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/2c44293b5f7342129e56c475dffb3040.jpg',
        '探寻教育本质的经典论述', 1),
       ('计算机网络安全原理', 8, 32.80,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/2e8c3433949c4cb19d27456a614ca67c.jpg',
        '网络安全领域的权威教材', 1),
       ('围城', 1, 32.50,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/2ec72b93db1841d9b6e0c6b2af2f9143.jpg',
        '洞察人性的现代文学经典', 1),
       ('物换星移', 3, 14.30,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/304b20bccd914d2cb59a3e79ce910d00.jpg',
        '奇幻世界中的人文思考', 1),
       ('人的宗教', 5, 13.70,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/319be3e60e454d88bec40b827abc921a.jpg',
        '探索宗教与人性的智慧之书', 1),
       ('海底两万里', 3, 22.80,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/31d854a31647482abe2dbe00bded1bb4.jpg',
        '科幻冒险文学的不朽经典', 1),
       ('爱上莫奈', 6, 24.90,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/33e8c1d0d27c45eca80b7b2e55f2388a.jpg',
        '领略印象派大师的艺术魅力', 1),
       ('财务管理', 9, 18.70,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/3655d67137ac438fbca3aeecfc430cbc.jpg',
        '财务管控的实用入门宝典', 1),
       ('经济学基础', 9, 16.10,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/3c71677e4bde4a7eaa8b644eeb4d2a71.jpg',
        '经济学入门的通俗经典', 1),
       ('中国通史', 2, 31.40,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/412baff597ad4525bbcd6474b8198ed4.jpg',
        '梳理中华文明的发展脉络', 1),
       ('哲学与时代', 5, 13.20,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/42c2ff2757a24b2e8696944d90f3187a.jpg',
        '连接哲学与时代的思想桥梁', 1),
       ('管理经济学', 9, 31.60,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/49d0e9011c494ee68cf288ade992afc6.jpg',
        '管理决策的经济学思维指南', 1),
       ('城中城', 3, 33.50,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/5436f8f419ee4f209efca4df5bb9145f.jpg',
        '科幻外壳下的社会隐喻', 1),
       ('世界美术名著二十讲', 6, 11.40,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/56083379fba44a1fb7e1979af01f4c5e.jpg',
        '漫游世界美术的经典之作', 1),
       ('经济管理基础', 9, 51.40,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/5dc073d6dbb04f879b2d91644d57d6a9.jpg',
        '经济管理的系统入门教材', 1),
       ('财务管理', 9, 27.50,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/69eb140f955e415ea46ed007b6b61e73.jpg',
        '企业财务运营的实战手册', 1),
       ('将进酒', 6, 19.90,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/70fe598a53184f6c84e12fd1e8ae11d5.jpg',
        '诗酒趁年华的豪放之作', 1),
       ('中国社会科学', 4, 26.40,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/6a5dbe7737084c0da8f051b4ec6cf80f.jpg',
        '中国社会科学的权威探索', 1),
       ('阿勒泰的初夏', 6, 24.10,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/7254f8598c8a4e44927aac01fff62ac7.jpg',
        '阿勒泰草原的诗意画卷', 1),
       ('爱的教育', 7, 22.10,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/75b4458463bc478f914c6851a6f5cbdc.jpg',
        '滋养心灵的儿童教育经典', 1),
       ('计算机科学引论', 7, 20.30,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/777416c3a74b4447b3bd536360c73ced.jpg',
        '计算机科学的入门必读', 1),
       ('月球漂流', 3, 11.84,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/7b72cfdf73ff43c79ac4182cdabc1400.jpg',
        '月球探险的科幻精彩之作', 1),
       ('三国志', 1, 18.84,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/7b824a08a25c46c9afc9257f1b87bc3b.jpg',
        '三国风云的史诗级巨著', 1),
       ('暮星归途', 3, 22.91,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/7be6fa8a19834da8862073f99806ede5.jpg',
        '星际归途的热血科幻故事', 1),
       ('基础医学概论', 10, 15.80,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/8544222c8fea4779b5b7830cc25159b5.jpg',
        '医学基础的系统入门教材', 1),
       ('微积分(经济管理)', 9, 21.88,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/884c9b96678a4044b475799d1cab710d.jpg',
        '经管类微积分的实用教程', 1),
       ('道德与法治(七年级上册)', 7, 32.10,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/89ae2b0512d8456bb43277b0669fac13.jpg',
        '青少年品德培养的核心教材', 1),
       ('医学影像学', 10, 21.13,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/8f56c0588b134ec7ab1a1d3b6d5806c5.jpg',
        '医学影像诊断的权威指南', 1),
       ('变宋', 2, 23.33,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/990238321269444c9fab2edbe6b353b3.jpg',
        '重构宋史的历史小说佳作', 1),
       ('远方的宁静', 6, 17.86,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/a0e54c91eeb747729e75a4c593b502e1.jpg',
        '追寻内心宁静的治愈之作', 1),
       ('朝花夕拾', 1, 25.55,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/a2529d0a4ab4433abafb9a2997e623d5.jpg',
        '回忆性散文的经典范本', 1),
       ('需求侧管理', 9, 10.81,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/a62a1bd9368e4f178faf5405b8579de4.jpg',
        '需求侧改革的实践指南', 1),
       ('社会主义从空想到科学的发展', 4, 24.77,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/a9fb26d7b4ae4619bba7c57eb69ec699.jpg',
        '社会主义思想的经典著作', 1),
       ('计算机网络', 8, 16.4,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/aac3ce27fbd64fe6a3ee8d00a1e84032.jpg',
        '计算机网络的经典教材', 1),
       ('医学遗传学', 10, 13.67,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/ac716d4444254c2d9b153ca59bffc15a.jpg',
        '遗传学与医学的交叉宝典', 1),
       ('世界是如何思考的', 5, 14.22,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/ad4c530bfc5745f18c5e1a36ee4fcc3d.jpg',
        '探索全球思维方式的著作', 1),
       ('计算机组成原理', 8, 22.33,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/b2f5f0b2371d46f38636431d86bf7000.jpg',
        '计算机组成的权威教材', 1),
       ('恒封纪元', 3, 22.89,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/b84de9a52645446eb55a10cc0f158b8e.jpg',
        '史诗级科幻，构建恢弘世界观', 1),
       ('阅读教育', 7, 14.82,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/b93ddab26915441ebcfc7a89005234d0.jpg',
        '深耕阅读教育的实用指南', 1),
       ('科学,文化与社会', 4, 16.77,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/bbeefe45b4d74f9ca491903955871d21.jpg',
        '科学与人文交融的经典论述', 1),
       ('三体', 3, 23.11,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/c17c5633661b4022bbd9b855288b4808.jpg',
        '中国科幻的里程碑式巨著', 1),
       ('临床医学概论', 10, 16.70,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/cc6b09c18d2f46e79e4fca4382f33f6f.jpg',
        '临床医学入门的权威教材', 1),
       ('计算机应用基础', 8, 21.80,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/d503e8e633d94b8d874caf104a57117b.jpg',
        '计算机应用的实用入门宝典', 1),
       ('计算机科学概论', 8, 20.80,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/d8adbfaab41d4821b44e20b15a50a3a9.jpg',
        '计算机科学的启蒙经典', 1),
       ('现代社会学理论', 4, 18.99,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/dfa541f06e8f4b04b9f885cdd8c47ec3.jpg',
        '解析现代社会的理论力作', 1),
       ('学前教育学', 7, 31.23,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/e34cd702a1f64447bf16e3a30f45b6ad.jpg',
        '学前教育领域的经典教材', 1),
       ('易经', 5, 22.22,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/ed2dd731e6804be6b68350c5cc31baf4.jpg',
        '中华智慧的千古经典之作', 1),
       ('教育学', 7, 20.01,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/f641b72042b148cf9b31074be55e68bb.jpg',
        '教育学领域的奠基性著作', 1),
       ('哲学,宗教与文化', 5, 13.31,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/f8d34fbf4ad043908dc134628c4289fd.jpg',
        '跨界融合的哲学智慧之书', 1),
       ('大唐300年', 2, 25.77,
        'https://neko-book.oss-cn-hangzhou.aliyuncs.com/book_img/f96f782331414250aefc54c2c22b2084.jpg',
        '全景展现大唐盛世的史诗', 1);

DROP TABLE IF EXISTS users;
CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 自增主键
    name      VARCHAR(32) NOT NULL,                                -- 姓名
    username  VARCHAR(32) NOT NULL,                                -- 用户名
    password  VARCHAR(64) NOT NULL,                                -- 密码
    phone     VARCHAR(11) NOT NULL,                                -- 手机号
    sex       VARCHAR(2)  NOT NULL,                                -- 性别
    id_number VARCHAR(18) NOT NULL,                                -- 身份证号
    status    INT         NOT NULL DEFAULT 1,                      -- 状态 0:禁用，1:启用
    CONSTRAINT idx_username UNIQUE (username)                      -- 唯一索引
);

INSERT INTO users (name, username, password, phone, sex, id_number, status)
VALUES ('张三', 'zhangsan', '123456', '12345678901', '1', '110101199001010047', 1)

